require "user.options"
require "user.plugins"
require "user.colorscheme"
require "user.nvim-tree"
require "user.bufferline"
require "user.toggleterm"
require "user.treesitter"
require "user.lsp"
require "user.lualine"
require "user.comment"
require "user.keymaps"
require "user.telescope"
require "user.autopairs"
require "user.ts-autotag"

